name: Docker CI/CD

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Building part
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: 23 (2025-12-16)
    steps:
      - name: Chekout repository
        uses: actions/checkout@v6

      - name: Setting up Docker builder
        uses: docker/setup-buildx-action@v3

      - name: Setting up Docker login
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERUSER }}
          password: ${{ secrets.DOCKERPASSWORD }}

      - name: Docker build and push
        uses: docker/build-push-action@v6
        with:
          context: './23 (2025-12-16)'
          push: true
          tags: |
            ${{ vars.DOCKERUSER }}/devopsua6-pub:latest
            ${{ vars.DOCKERUSER }}/devopsua6-pub:${{ github.sha }}
      